%La exportación de resultados a excel se ha comentado para evitar su
%ejecución retierada.
%% Pregunta I
df=setII('simce.csv','prior_sep.csv');
sprintf('Respuesta pregunta 1')
[est_descript_g ,est_descript_x_rural ,est_descript_x_grup, est_descript_x_depe ] = df.est_descript();
% export_to_excel("Total de Datos",est_descript_g(:,1),est_descript_g(:,2),est_descript_g(:,3),est_descript_g(:,4),est_descript_g(:,5),...
%     "tabla21",{'Rango_de_Datos','Observaciones',...
%     'Promedio','Desv_Estandar','Minimo','Maximo'});
%  
%  export_to_excel(["Urbano";"Rural"],est_descript_x_rural(:,1),est_descript_x_rural(:,2),est_descript_x_rural(:,3),est_descript_x_rural(:,4),est_descript_x_rural(:,5),...
%      "tabla22",{'Rango_de_Datos','Observaciones',...
%      'Promedio','Desv_Estandar','Minimo','Maximo'});
% export_to_excel(["Municipal";"Particular Subvencionado";"Particular Pagado"],est_descript_x_depe(:,1),...
%     est_descript_x_depe(:,2),est_descript_x_depe(:,3),est_descript_x_depe(:,4),est_descript_x_depe(:,5),...
%     "tabla23",{'Rango_de_Datos','Observaciones',...
%     'Promedio','Desv_Estandar','Minimo','Maximo'});
% export_to_excel(["Bajo";"Medio bajo";"Medio"; "Medio Alto";"Alto"],est_descript_x_grup(:,1),...
%     est_descript_x_grup(:,2),est_descript_x_grup(:,3),est_descript_x_grup(:,4),est_descript_x_grup(:,5),...
%     "tabla24",{'Rango_de_Datos','Observaciones',...
%     'Promedio','Desv_Estandar','Minimo','Maximo'});
%% Pregunta II
sprintf('Respuesta pregunta 2')
[coef, err_est, r2] = df.mco_est([ones(df.obs,1) df.tabla{:,"prom_prioritario" } df.dummie_depe(:,2:end) df.dummie_grupo(:,2:end) df.dummie_rural(:,2) ])
% export_to_excel(['beta0';'beta1';'beta2';'beta3';...
%     'beta4';'beta5';'beta6';...
%     'beta7';'beta8'],coef,err_est,"tabla25",{'coeficiente','valor','error_estandar'});
%% Pregunta III
sprintf('Respuesta pregunta 3')
prioritarios = df.tabla{:,end} .* 100;
[coef, err_est, r2]=df.mco_est([ones(df.obs,1)  prioritarios  df.dummie_depe(:,2:end) df.dummie_grupo(:,2:end)  df.dummie_rural(:,2) ])
% export_to_excel(['beta0';'beta1';'beta2';'beta3';...
%     'beta4';'beta5';'beta6';...
%     'beta7';'beta8'],coef,err_est,"tabla26",{'coeficiente','valor','error_estandar'});

%% Pregunta IV
sprintf('Respuesta pregunta 4')
prioritarios_2 = prioritarios .^2;
[coef, err_est, r2 , mvarcov]=df.mco_est([ones(df.obs,1)  prioritarios prioritarios_2  df.dummie_depe(:,2:end) df.dummie_grupo(:,2:end)  df.dummie_rural(:,2)] );
% export_to_excel(['beta0';'beta1';'beta2';'beta3';...
%     'beta4';'beta5';'beta6';...
%     'beta7';'beta8';'beta9'],coef,err_est,"tabla27",{'coeficiente','valor','error_estandar'});

%% Pregunta V
sprintf('Respuesta pregunta 5 y 6')
efecto_marginal = df.efc_marginal(prioritarios,coef,mvarcov);


